# Generated by Django 4.2.7 on 2023-11-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='title',
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='content_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='content_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='title_tr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
