# Generated by Django 4.2.7 on 2023-12-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Customer'), (1, 'Admin'), (2, 'Super Admin')], default=0, null=True),
        ),
    ]
