import type { AppProps } from 'next/app';
import { ReactElement, ReactNode, useEffect } from 'react';
import DefaultLayout from '../components/Layouts/DefaultLayout';
import { ToastContainer } from 'react-toastify';
import { Provider } from 'react-redux';
import store from '../store/index';
import Head from 'next/head';
import { appWithI18Next } from 'ni18n';
import { ni18nConfig } from 'ni18n.config.ts';
import eventEmitter from '@/pages/api/events';

// Perfect Scrollbar
import 'react-perfect-scrollbar/dist/css/styles.css';
import '../styles/tailwind.css';
import { NextPage } from 'next';
import { useRouter } from 'next/router';

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
    getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
    Component: NextPageWithLayout;
};

import { refreshTokenAfterInterval } from './api';

const App = ({ Component, pageProps: { session, ...pageProps } }: AppPropsWithLayout) => {
    const getLayout = Component.getLayout ?? ((page) => <DefaultLayout>{page}</DefaultLayout>);
    const router = useRouter();

    useEffect(() => {
        function handleUnauthorized() {
            router.push('/auth/login');
        }

        eventEmitter.on('unauthorized', handleUnauthorized);
        return () => {
            eventEmitter.off('unauthorized', handleUnauthorized);
        };
    }, [router]);

    useEffect(() => {
        refreshTokenAfterInterval();
    }, []);

    return (
        <Provider store={store}>
            <Head>
                <title>SerPer Interpreter</title>
                <meta charSet="UTF-8" />
                <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            {getLayout(<Component {...pageProps} />)}
            <ToastContainer />
        </Provider>
    );
};
export default appWithI18Next(App, ni18nConfig);
